### PR TITLE
Added a section about LFPy

### PR DESCRIPTION
**Pull request by espenhgn**
Hi, we've added a section about LFPy, a forward-modeling framework for extracellular potentials from multicompartment neuron models build in Python.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Great!  I bet the logo originated in some vector format.  I wonder if you still have original (eg svg)?

**Comment by yarikoptic** [comment]
ah -- actually found it in the sources (Logo_final.ai?) so I have it converted to .svg now

**Comment by yarikoptic** [comment]
I have reworked your commit to not include the .png and added the .svg in the next commit 131b6586c963ec6e62c818675eb53acea1d2271c.  Now it is all pushed, so I am closing this one manually.

**Comment by espenhgn** [comment]
Thanks, great:-)

Espen

**Pull request closed without merging**
