### PR TITLE
Added G-Node Data API Python Client

### PR DESCRIPTION
**Pull request by michaelfsp**

### CODE REVIEW

**Comment by yarikoptic** [comment]
hm

http://g-node.github.com/python-gnode-client
points to 404 There isn't a GitHub Page hosted here, sorry.

and http://g-node.github.com/ only gives "BLABLA" ;-)

are they under your control?  it would be cool if you could change the
root one to something which would talk about future
python-gnode-client... my problem atm that url is too long (and
non-existent anyways atm) and I have no time to play with it... so 
I will go with a short top url for now

On Thu, 11 Oct 2012, Michael Ferreira S. Pereira wrote:

> ---
> 
> ```
> You can merge this Pull Request by running:
> ```
> 
>    git pull https://github.com/michaelfsp/nipy-artwork master
> 
>    Or view, comment on, or merge it at:
> 
>      [1]https://github.com/nipy/nipy-artwork/pull/15
> 
> ```
> Commit Summary
> ```

## 

Yaroslav O. Halchenko
Postdoctoral Fellow,   Department of Psychological and Brain Sciences
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by michaelfsp** [comment]
Hey Yarik!

Yeah, sorry I should have mentioned that. I am aware that the link I used
is empty but I will put up a page tomorrow. It would be best if we would
use that link instead of the g-node.github.com as I am not sure whether I
can edit the latter and it is not specific to the client.

Would that solve the problem?

Thanks

Cheers,

Michael

**Comment by yarikoptic** [comment]
heh... printing already with a short one (need to leave home very soon
so time is pressing)... problem was is that long urls obscure the
"heading" -- people will figure out then, and I bet it should be
possible to fix it up... sorry about that 

btw- - I have pushed my changes

On Thu, 11 Oct 2012, Michael Ferreira S. Pereira wrote:

>    Hey Yarik!
> 
>    Yeah, sorry I should have mentioned that. I am aware that the link I used
>    is empty but I will put up a page tomorrow. It would be best if we would
>    use that link instead of the g-node.github.com as I am not sure whether I
>    can edit the latter and it is not specific to the client.
> 
>    Would that solve the problem?
> 
>    Thanks
> 
>    Cheers,
> 
>    Michael

## 

Yaroslav O. Halchenko
Postdoctoral Fellow,   Department of Psychological and Brain Sciences
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by michaelfsp** [comment]
OK, no worries! I will figure out a way of having a webpage at that URL.

Thanks for your work!

Cheers,

Michael

**Comment by yarikoptic** [comment]
thanks for the contributions!

**Comment by michaelfsp** [comment]
my pleasure ;-)

Michael

**Pull request merged**
