### PR TITLE
Fall cleanup

### PR DESCRIPTION
**Pull request by zyv**
Hi,

Here I am with some cleanup patches...

Z.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Please make sure that flyers still render well after removal of pdf's
Usually I was pruning them myself but in the cases when I had to stay with custom rendered one

"Yury V. Zaytsev" notifications@github.com wrote:

> Hi,
> 
> Here I am with some cleanup patches...
> 
> Z.
> 
> You can merge this Pull Request by running:
> 
>  git pull https://github.com/zyv/nipy-artwork master
> 
> Or you can view, comment on it, or merge it online at:
> 
>  https://github.com/nipy/nipy-artwork/pull/16
> 
> -- Commit Summary --
> - eppy: \textregistered is invalid in math mode, wrap around with
>   \textrm{}
>   - pics: update .gitignore
>   - pics: remove generated files
>   - flier: updated .gitignore
>   - license: add myself to authors
> 
> -- File Changes --
> 
> M LICENSE (1)
> M flier/.gitignore (5)
> M flier/eppy-handout.tex (4)
> M pics/.gitignore (2)
> D pics/gnode_logo.pdf (0)
> D pics/nitime_logo.pdf (0)
> D pics/nitime_network.pdf (483)
> 
> -- Patch Links --
> 
> https://github.com/nipy/nipy-artwork/pull/16.patch
> https://github.com/nipy/nipy-artwork/pull/16.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nipy/nipy-artwork/pull/16

## 

Sent from a phone which beats iPhone.

**Comment by zyv** [comment]
Hi yoh,

I checked and it LGTM, but you can just drop this patch if on your configuration they don't render correctly. I was just annoyed that git showed that these files changed after make, because binaries were pre-committed.

Z.

**Comment by yarikoptic** [comment]
what is LGTM?

there is a slight screw up with the GNode logo -- rendered automagically
version lacks nice contours ... but I guess that is ok since at this
resolution there would be no difference in printed product.  so I have
merged/pushed

thanks

On Tue, 20 Nov 2012, Yury V. Zaytsev wrote:

>    Hi yoh,
> 
>    I checked and it LGTM, but you can just drop this patch if on your
>    configuration they don't render correctly. I was just annoyed that git
>    showed that these files changed after make, because binaries were
>    pre-committed.
> 
>    Z.
> 
>    —
>    Reply to this email directly or [1]view it on GitHub.
> 
> References
> 
>    Visible links
> 1. https://github.com/nipy/nipy-artwork/pull/16#issuecomment-10561948

## 

Yaroslav O. Halchenko
Postdoctoral Fellow,   Department of Psychological and Brain Sciences
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by zyv** [comment]
On Tue, 2012-11-20 at 09:48 -0800, Yaroslav Halchenko wrote:

> what is LGTM?

Looks Good To Me >;-) code review slang, sorry about that.

> there is a slight screw up with the GNode logo -- rendered
> automagically version lacks nice contours ... but I guess that is ok
> since at this resolution there would be no difference in printed
> product.  so I have merged/pushed

Heh, I didn't even notice... You're welcome, more requests are coming
through Andrew w.r.t. the simulators handout.

Z.

## 

Sincerely yours,
Yury V. Zaytsev

**Pull request merged**
