### PR TITLE
 neo and OpenElectrophy

### PR DESCRIPTION
**Pull request by samuelgarcia**
I have added OpenElectrophy and neo (It is a quick and dirty).
I am not a latex user so sorry I can't see the result. Sorry for that.

Thank you for this flyer.

Samuel

### CODE REVIEW

**Comment by yarikoptic** [comment]
Cool - thanks!  I can work from there.  Few points:
- for OpenElectrophy_logo.png -- do you may be have a vectorized original or at least a png with a transparent background?
- neo_logo.png -- usually it is better not to commit derived/converted from .svg images -- inkscape can do that automagically (there is a Makefile);)

**Comment by samuelgarcia** [comment]
On 02/10/2012 14:44, Yaroslav Halchenko wrote:

> Cool - thanks! I can work from there. Few points:
> - for OpenElectrophy_logo.png -- do you may be have a vectorized
>   original or at least a png with a transparent background?
> 
> Unfortunately no. I lost it some years ago before (svn and git ages)
> - neo_logo.png -- usually it is better not to commit
>   derived/converted from .svg images -- inkscape can do that
>   automagically (there is a Makefile);)
> 
> Sorry. You can delete.

Thanks a lot for the flier.

Samuel

**Comment by yarikoptic** [comment]
ah -- wouldn't openelectrophy be worth a screenshot? ;)  what would be
your favorite on?

## 

Yaroslav O. Halchenko
Postdoctoral Fellow,   Department of Psychological and Brain Sciences
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by samuelgarcia** [comment]
Is this OK ?

**Comment by yarikoptic** [comment]
I am afraid this would be too overloaded to look anyhow informative
within 1 column ;-)  What about just "Filtered signal" + "Average
waveforms" + Steps/Units list at the bottom?

On Tue, 02 Oct 2012, Garcia Samuel wrote:

>    Is this OK ?
> 
>    —
>    Reply to this email directly or [1]view it on GitHub.
> 
> References
> 
>    Visible links
> 1. https://github.com/nipy/nipy-artwork/pull/10#issuecomment-9072162

## 

Yaroslav O. Halchenko
Postdoctoral Fellow,   Department of Psychological and Brain Sciences
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by samuelgarcia** [comment]
You ask me to forget the N dimensional viewer : the angular piece of OE ?

OK, point for you.

Thanks again for doing this.

I hope it is not too late.

Samuel

**Comment by samuelgarcia** [comment]
Oh, sorry. I have just seen the final PDF. I prefer the one with first
screenshot!! It is perfect, forget last email.

Thanks again, have good at sfn.

Samuel

**Comment by yarikoptic** [comment]
On Wed, 03 Oct 2012, Garcia Samuel wrote:

>    Oh, sorry. I have just seen the final PDF. I prefer the one with first
>    screenshot!! It is perfect, forget last email.

as you wish ;)  but do not hesitate to submit fixes/improvements -- PDF
is not yet 'final'.  I have made a test print -- indeed it is ok'ish
with a full blown screenshot as well, so I left it was is 

>    Thanks again, have good at sfn.

## Thanks ;-)

Yaroslav O. Halchenko
Postdoctoral Fellow,   Department of Psychological and Brain Sciences
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Pull request merged**
