### PR TITLE
Modified <svg> tag in nitime_logo.svg to make it readable by inkscape

### PR DESCRIPTION
**Pull request by campagnola**
Note: the original SVG was generated with Adobe Illustrator. It is possible these changes will make the file unopenable in Illustrator.

### CODE REVIEW

**Comment by yarikoptic** [comment]
@arokem are you still in possession of the mighty AI to check if this SVG is openable there? (although not sure if we should care at all?)

btw it still spits out a warning for me

```
/home/yoh/proj/nipy/nipy-suite/nipy-artwork/pics/nitime_logo.svg:1694: namespace error : Namespace prefix xlink for href on image is not defined
RK5CYII=" transform="matrix(0.0945 0 0 0.0935 42.2983 10.8398)">
```

**Comment by arokem** [comment]
It is indeed. Still looks great :-)

**Comment by yarikoptic** [comment]
yeah -- looked good to me to... ok --merging and then will reload/save in inkscape to avoid the error above

**Comment by yarikoptic** [comment]
btw thanks @arokem ;)

**Pull request merged**
